"""CLI entry point — argparse, logging setup, orchestration lifecycle."""
import argparse
import platform
import sys
import time
from pathlib import Path

# Module-attribute access so @patch("orchestrator.<mod>.<name>") propagates.
from . import bug_variant, git_ops, item, loops, output, runner, tasks
from .config import (
    DEFAULT_TEST_CMD, MAX_CRITIC_ITERATIONS, MAX_ITERATIONS,
)
from .prompts import format_elapsed
from .runner import extract_failure_count


def main():
    parser = argparse.ArgumentParser(
        description="Orchestrator — implement tasks via Claude, verify with tests and Critic, "
                    "commit to Git, resume on restart"
    )
    parser.add_argument(
        "--tasks", required=True,
        help=(
            "Work-item source: path to a .md file, .json/.yaml file, or a "
            "directory. Directories are scanned for both T<NN>-*.md (tasks) "
            "and B<NN>-*.md (bugs); Class B bugs are skipped with a log entry."
        ),
    )
    parser.add_argument(
        "--test-cmd", default=DEFAULT_TEST_CMD,
        help=(
            "Test command to execute. Defaults to '%(default)s' — a project-owned "
            "runner generated by /scaffold that dispatches to whatever test tools the "
            "tech stack uses (pytest, flutter, mvn, gradle, ...). Override for "
            "projects that use a different entry point."
        ),
    )
    parser.add_argument(
        "--project-dir", default=".",
        help="Project root directory — must be a git repository (default: current directory)",
    )
    parser.add_argument(
        "--max-iterations", type=int, default=MAX_ITERATIONS,
        help=f"Max Ralph Loop retries per task (default: {MAX_ITERATIONS})",
    )
    parser.add_argument(
        "--max-critic-iterations", type=int, default=MAX_CRITIC_ITERATIONS,
        help=f"Max Critic review cycles per task (default: {MAX_CRITIC_ITERATIONS})",
    )
    parser.add_argument(
        "--filter", default=None, dest="task_filter",
        help="Only run tasks whose ID contains this string",
    )
    args = parser.parse_args()

    task_list = item.load_items(args.tasks)
    if args.task_filter:
        task_list = [t for t in task_list if args.task_filter.lower() in t["id"].lower()]

    # Filter Class B bugs — handled manually per workflow-bugs skill.
    class_b_bugs = [t for t in task_list if bug_variant.is_class_b(t)]
    if class_b_bugs:
        print(f"[SKIP] {len(class_b_bugs)} Class B bug(s) not processed by orchestrator:")
        for t in class_b_bugs:
            print(f"       - {t['id']}  (Class B bugs are manual — see workflow-bugs skill)")
        task_list = [t for t in task_list if t not in class_b_bugs]

    # Stable sort: tasks before bugs within each Epic, then by ID.
    task_list.sort(key=lambda t: (t.get("epic", ""), 0 if t.get("type") == "task" else 1, t["id"]))

    if not task_list:
        print("[ERROR] No work items found. Check --tasks path or --filter value.", file=sys.stderr)
        sys.exit(1)

    project_dir = str(Path(args.project_dir).resolve())

    # ── Log files ─────────────────────────────────────────────
    log_dir = Path(project_dir) / "logs"
    log_dir.mkdir(parents=True, exist_ok=True)
    timestamp     = time.strftime("%Y-%m-%d-%H-%M")
    log_path      = log_dir / f"orchestrator-{timestamp}.log"
    progress_path = log_dir / f"orchestrator-{timestamp}.progress.log"

    log_file      = open(log_path,      "w", encoding="utf-8", errors="replace", buffering=1)
    progress_file = open(progress_path, "w", encoding="utf-8", errors="replace", buffering=1)
    progress_filter = output._ProgressFilter(progress_file)

    _orig_stdout, _orig_stderr = sys.stdout, sys.stderr
    sys.stdout = output._Tee(_orig_stdout, log_file, progress_filter)
    sys.stderr = output._Tee(_orig_stderr, log_file)

    log_rel      = str(log_path.relative_to(project_dir))
    progress_rel = str(progress_path.relative_to(project_dir))
    if platform.system() == "Windows":
        log_rel      = log_rel.replace("/", "\\")
        progress_rel = progress_rel.replace("/", "\\")
        watch_cmd    = f"Get-Content {log_rel} -Wait -Tail 50 -Encoding utf8"
    else:
        watch_cmd = f"tail -f {log_rel}"
    print(f"[Log]      {log_rel}")
    print(f"[Progress] {progress_rel}")
    print(f"           Watch: {watch_cmd}\n")

    try:
        _run(args, task_list, project_dir, log_path)
    finally:
        sys.stdout = _orig_stdout
        sys.stderr = _orig_stderr
        log_file.close()
        progress_filter.close()


def _run(args, task_list, project_dir: str, log_path) -> None:
    # ── Prerequisite check (REQ-29) ───────────────────────────
    test_doc = tasks.find_test_doc(args.tasks, project_dir)
    test_doc_content = test_doc.read_text(encoding="utf-8")
    print(f"[Check] Test design doc: {test_doc.name} — OK")

    # ── Prerequisite check: default test runner exists (REQ-40) ─
    if args.test_cmd == DEFAULT_TEST_CMD and not (Path(project_dir) / "scripts" / "test.py").exists():
        print(
            f"[ERROR] scripts/test.py not found in {project_dir}.\n"
            f"        The default --test-cmd ('{DEFAULT_TEST_CMD}') expects a\n"
            f"        project-owned runner generated by /scaffold. Either run\n"
            f"        /scaffold <N> first, or pass an explicit --test-cmd.",
            file=sys.stderr,
        )
        sys.exit(1)

    # ── Resume check ─────────────────────────────────────────
    tasks_to_run, revert_context = git_ops.resume_check(task_list, args.test_cmd, project_dir)

    if not tasks_to_run:
        print("All tasks already completed — nothing to do.")
        sys.exit(0)

    print(f"\nOrchestrator starting")
    print(f"  Tasks              : {len(tasks_to_run)} (of {len(task_list)} total)")
    print(f"  Project dir        : {project_dir}")
    print(f"  Test command       : {args.test_cmd}")
    print(f"  Max loop retries   : {args.max_iterations}")
    print(f"  Max critic cycles  : {args.max_critic_iterations}")

    results: list[dict] = []
    total_tasks = len(tasks_to_run)

    for i, task in enumerate(tasks_to_run):
        stats: dict = {}
        ok = loops.critic_loop(
            task, args.test_cmd, project_dir,
            args.max_iterations, args.max_critic_iterations,
            revert_context=revert_context if i == 0 else None,
            test_doc_content=test_doc_content,
            task_index=i + 1,
            total_tasks=total_tasks,
            stats_out=stats,
        )

        if ok:
            committed = git_ops.git_commit_task(task["id"], project_dir)
            if not committed:
                print(f"  [!] Git commit failed for '{task['id']}' — continuing anyway")

        results.append({
            "id":            task["id"],
            "passed":        ok,
            "elapsed":       stats.get("elapsed", 0.0),
            "critic_cycles": stats.get("critic_cycles", 0),
            "reason":        stats.get("reason", "unknown"),
        })

        passed_so_far = sum(1 for r in results if r["passed"])
        failed_so_far = len(results) - passed_so_far
        remaining     = total_tasks - (i + 1)
        print(f"  Progress: {i + 1}/{total_tasks}  |  "
              f"passed: {passed_so_far}  failed: {failed_so_far}"
              + (f"  |  next: {tasks_to_run[i + 1]['id']}" if remaining else ""))

    # ── Final verification (REQ-34) ───────────────────────────
    print(f"\n{'='*64}")
    print("  FINAL VERIFICATION")
    print(f"{'='*64}")
    print(f"\n[Final]  {args.test_cmd}")
    final_passed, final_output = runner.run_tests(args.test_cmd, project_dir)
    if final_passed:
        print("  [OK] Full test suite passed")
    else:
        fail_count = extract_failure_count(final_output)
        count_str  = str(fail_count) if fail_count is not None else "?"
        print(f"  [FAIL] {count_str} failure(s) in full suite")

    # ── Summary table ─────────────────────────────────────────
    col = max((len(r["id"]) for r in results), default=10)
    sep = "─" * (col + 38)
    print(f"\n{'='*64}")
    print("  ORCHESTRATOR SUMMARY")
    print(f"{'='*64}")
    print(f"  {'Task':<{col}}  {'Status':<8}  {'Time':>7}  {'Critic'}")
    print(f"  {sep}")
    total_secs = 0.0
    for r in results:
        state_str = "PASSED" if r["passed"] else "FAILED"
        elapsed   = format_elapsed(r["elapsed"])
        cycles    = (f"{r['critic_cycles']} cycle{'s' if r['critic_cycles'] != 1 else ''}"
                     if r["critic_cycles"] else f"— ({r['reason']})")
        print(f"  {r['id']:<{col}}  {state_str:<8}  {elapsed:>7}  {cycles}")
        total_secs += r["elapsed"]
    print(f"  {sep}")
    passed_count = sum(1 for r in results if r["passed"])
    failed_count = len(results) - passed_count
    suite_str    = "PASS" if final_passed else "FAIL"
    print(f"  {passed_count} passed  {failed_count} failed  |  "
          f"Total: {format_elapsed(total_secs)}  |  Suite: {suite_str}")
    print(f"{'='*64}\n")

    sys.exit(0 if failed_count == 0 and final_passed else 1)
